name: Sugerir melhoria
description: Proponha uma funcionalidade ou melhoria.
title: "[Melhoria]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema
      description: Que necessidade esta proposta resolve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Solução proposta
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
